spring:
  application:
    name: notificationMS
  datasource:
    url: jdbc:mysql://localhost:3306/twitter_notification
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none # or create, create-drop, none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # or your specific dialect


server:
  port: 8084 # or your desired port

logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
    your:
      package: DEBUG # Replace 'your.package' with your application's package